                           <div id="legal-scroll">
                                    <h1>Review legal</h1>
                                    <p><b>Red/E Marketing, LLC </b></p>
                                    <p><b>Terms &amp; Conditions of Services</b></p>
                                    <p><b>PLEASE READ THESE SHOPPER MARKETING HUB, LLC D/B/A Red/E (“Red/E”) TERMS AND CONDITIONS OF SERVICES (THE “AGREEMENT”) CAREFULLY BEFORE USING THE SERVICES OFFERED BY Red/E, INCLUDING THE BINDING ARBITRATION PROVISION IN SECTION 18(H). BY CLICKING THE “SUBMIT” BUTTON OR BY USING THE WEBSITE </b><a target="_blank" href="http://rede-marketing.com"><b>WWW.REDE-MARKETING.COM</b></a><b> (THE “SITE”) OR THE SERVICES OFFERED ON THE SITE IN ANY MANNER (THE FIRST DATE ON WHICH EITHER OF THESE EVENTS OCCURS, THE “EFFECTIVE DATE”), YOU OR THE ENTITY YOU REPRESENT (“CLIENT” OR “YOU”) AGREE THAT YOU HAVE READ AND AGREE TO BE BOUND BY AND A PARTY TO THE TERMS AND CONDITIONS OF THIS AGREEMENT. YOU REPRESENT AND WARRANT THAT YOU ARE AUTHORIZED TO BIND CLIENT. USE OF Red/E’S SERVICES IS EXPRESSLY CONDITIONED UPON CLIENT’S ASSENT TO ALL THE TERMS AND CONDITIONS OF THIS AGREEMENT, ANY ADDITIONAL GUIDELINES, RESTRICTIONS, OR RULES THAT MAY BE POSTED IN CONNECTION WITH SPECIFIC SECTIONS OR SERVICES OF REDE-MARKETING.COM. ALL SUCH ADDITIONAL POSTED GUIDELINES, RESTRICTIONS, OR RULES ARE HEREBY INCORPORATED BY REFERENCE INTO THIS AGREEMENT. IF THE TERMS OF THIS AGREEMENT ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO SUCH TERMS. IF YOU DO NOT UNCONDITIONALLY AGREE TO ALL THE TERMS AND CONDITIONS OF THE AGREEMENT, NAVIGATE AWAY FROM THIS PAGE AND YOU WILL HAVE NO RIGHT TO USE THE SERVICES. UNLESS EXPRESSLY AGREED BY Red/E, NO CLIENT TERMS OR CONDITIONS WILL BE BINDING ON Red/E.</b></p>
                                    <p><span style="font-weight: 400;">This Agreement includes and hereby incorporates by reference the following (collectively, with this Agreement, the “</span><b>Terms of Service</b><span style="font-weight: 400;">”): </span></p>
                                    <ul>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">An Order (defined below).</span></li>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">Privacy Policy.</span></li>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">Terms of Use. </span></li>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">The following “</span><b>Service-Specific Terms</b><span style="font-weight: 400;">”:</span></li>
                                    </ul>
                                    <ul>
                                    <li style="list-style-type: none;">
                                    <ul>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">Design and Creative Terms of Service for Clients; </span></li>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">Social Media Marketing Terms of Service for Clients; and</span></li>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">IAB Standard Terms &amp; Conditions Version 3.0 (found at: </span><a target="_blank" href="http://www.iab.net/media/file/IAB_4As-tsandcs-FINAL.pdf"><span style="font-weight: 400;">http://www.iab.net/media/file/IAB_4As-tsandcs-FINAL.pdf</span></a><span style="font-weight: 400;">).</span></li>
                                    </ul>
                                    </li>
                                    </ul>
                                    <ul>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">Such agreements may be in effect and modified by Red/E from time to time.</span></li>
                                    </ul>
                                    <p><span style="font-weight: 400;">The Terms of Service are available at www.rede-marketing.com/legal/terms/. If there is any conflict or inconsistency between or among any of the Terms of Service with respect to a particular service provided hereunder, the following order of precedence shall govern: (i) the Order; (ii) the relevant Service-Specific Terms; (iii) this Agreement; (iv) the Privacy Policy; (v) the Terms of Use; and (vi) any other applicable terms and conditions. </span></p>
                                    <p><span style="font-weight: 400;">Red/E reserves the right, at its sole discretion, to modify or replace this Agreement, or change, suspend, or discontinue the Site, the related online platform (the “</span><b>Platform</b><span style="font-weight: 400;">”, the reference to which shall specifically include the Site, including without limitation, the availability of any feature, database, or content) and Red/E services at any time by posting a notice on the Platform, in the Terms of Service or by sending Client an email. It is Client’s responsibility to check this Agreement periodically for changes. Client’s continued use of the Platform or Red/E services provided under this Agreement following the posting of any changes to this Agreement constitutes acceptance of those changes.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Digital Signature; Account Registration.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">To use the Platform and the related services, you must register for a Red/E account (an “</span><b>Account</b><span style="font-weight: 400;">”). By registering for an Account, or by clicking to accept this Agreement when prompted on the Platform, you are deemed to have executed this Agreement and the other Terms of Service referenced herein electronically, effective on the date you register your Account or click to accept the terms of the Agreement, pursuant to the U.S. Electronic Signatures in Global and National Commerce Act (the E-Sign Act) (15 U.S.C. § 7001, et seq.). &nbsp;Your Account registration constitutes an acknowledgement that you can electronically receive, download, and print this Agreement, the other Terms of Service, and any amendments hereto or thereto.</span></p>
                                    <p><span style="font-weight: 400;">Red/E offers the Platform and related services for Client’s business purposes only, and not for personal, household, or consumer use. To use the Platform and related services, Client must have, and hereby represent that Client has, an independent business (whether it be as a corporation or other entity) and further represents that Client intends to use the Platform and related services for Client’s business purposes only. Client must comply with any licensing or registration requirements with respect to its business, and Client represents that it complies with all such requirements. Red/E reserves the right, in its sole discretion, to refuse, suspend, or revoke your access to the Platform or related services upon discovery that any information you provided through the Platform is not true, accurate, or complete, or such information or other conduct otherwise violates the Terms of Service, or for any other reason or no reason in Red/E’s sole discretion.</span></p>
                                    <p><span style="font-weight: 400;">You represent that you are not: (x) a citizen or resident of a geographic area in which access to or use of the Platform or related services is prohibited by applicable law, decree, regulation, treaty, or administrative act; (y) a citizen or resident of, or located in, a geographic area that is subject to U.S. or other sovereign country sanctions or embargoes; or (z) an individual, or an individual employed by or associated with an entity, identified on the U.S. Department of Commerce’s Denied Persons or Entity List, the U.S. Department of Treasury’s Specially Designated Nationals or Blocked Persons Lists, or the U.S. Department of State’s Debarred Parties List or otherwise ineligible to receive items subject to U.S. export control laws and regulations or other economic sanction rules of any sovereign nation. You agree that if your country of residence or other circumstances change such that the above representations are no longer accurate, that you will immediately cease using the Platform and the related services.</span></p>
                                    <p><span style="font-weight: 400;">You agree to provide true, accurate, and complete information on your Account profile and all registration and other forms you access on the Platform or provide to us and to update your information to maintain its truthfulness, accuracy, and completeness. &nbsp;You agree not to provide and to correct any information about your location, your business, your skills, or the services your business provides that is or becomes false or misleading. &nbsp;You agree not to register for more than one Account without express written permission from Red/E. &nbsp;</span></p>
                                    <p><span style="font-weight: 400;">You agree that you are responsible for protecting your password and controlling access to your Account. You agree that you will be responsible for all Orders placed or other actions that are taken through your Account.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Platform; Services &amp; Related Terms and Conditions.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Red/E provides the Platform to Clients to connect Clients with service providers (“</span><b>Vendors</b><span style="font-weight: 400;">”) to advertise Client’s products. Red/E offers Clients the opportunity to obtain the following Vendor services (collectively, “</span><b>Vendor Services</b><span style="font-weight: 400;">”) through its Platform: </span></p>
                                    <ul>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">On-pack product advertising.</span></li>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">Mobile media advertising, which is subject to IAB Standard Terms &amp; Conditions Version 3.0. The IAB terms and conditions can be found at: </span><a target="_blank" href="http://www.iab.net/media/file/IAB_4As-tsandcs-FINAL.pdf"><span style="font-weight: 400;">http://www.iab.net/media/file/IAB_4As-tsandcs-FINAL.pdf</span></a><span style="font-weight: 400;">.</span></li>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">Paid social media advertising, which are subject to the </span><span style="font-weight: 400;">Red/E Social Media Marketing Terms of Service</span><span style="font-weight: 400;"> and the IAB Standard Terms &amp; Conditions Version 3.0 (found at: http://www.iab.net/media/file/IAB_4As-tsandcs-FINAL.pdf).</span></li>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">Digital billboard advertising.</span></li>
                                    <li style="font-weight: 400;"><span style="font-weight: 400;">Security shroud media advertising. </span></li>
                                    </ul>
                                    <p><span style="font-weight: 400;">Red/E also provides a set of services to: (i) design and provide other creative services projects incidental to Vendor Services (“</span><b>Creative Services</b><span style="font-weight: 400;">”), subject to </span><span style="font-weight: 400;">Red/E Social Media Marketing Terms of Service</span><span style="font-weight: 400;">; (ii) scope Client’s requirements for Vendor Services; (ii) identify one or more appropriate Vendors to provide such Vendor Services; and (iv) provide additional assistance to Client in connection with the receipt of such Vendor Services, as may be required by mutual agreement (collectively, the “</span><b>Red/E Services</b><span style="font-weight: 400;">”, and together with any Vendor Services, the “</span><b>Services</b><span style="font-weight: 400;">”).</span></p>
                                    <p><span style="font-weight: 400;">In addition, Vendor Services are governed by the applicable Vendor terms and conditions that may apply to Client’s purchase. Mobile media advertising may also be subject to third-party licensing restrictions. For more information, </span><a target="_blank" href="mailto:info@rede-marketing.com"><span style="font-weight: 400;">info@rede-marketing.com</span></a><span style="font-weight: 400;">. </span></p>
                                    <ul>
                                    <li><b>Red/E Disclaimer of Responsibility for Vendor Services</b></li>
                                    </ul>
                                    <p><span style="font-weight: 400;">Client expressly acknowledges and agrees that all Vendors are independent contractors and are not employees, agents, partners or joint venturers of either Red/E or Client. Client further expressly acknowledges and agrees that the primary objective of the Platform is to serve as a venue for Clients to obtain from Vendors, and Vendors to provide to Clients, Vendor Services. For avoidance of doubt, Red/E does not provide nor is it obligated to provide Vendor Services, as those are provided by Vendors assigned to Client. </span></p>
                                    <p><span style="font-weight: 400;">Red/E Services are intended to merely assist Client in procuring and using the desired Vendor Services. Client assumes responsibility for working with Vendors and providing the required feedback, input and adherence to agreed-upon duration for a successful project. You acknowledge and agree that Red/E: (i) has no liability or obligation for any acts or omissions by you or any Vendor; (ii) has no control over Vendor Services offered or rendered by any Vendor; and (iii) makes no representations as to the reliability, capability, or qualifications of any Vendor or the quality, security, or legality of any Vendor Services, including any third-party materials, content or services provided to Client as part of the Vendor Services, and Red/E disclaims any and all liability relating thereto.</span></p>
                                    <p><span style="font-weight: 400;">Additionally, Client may be required to obtain retailer authorization for Vendor to successfully execute or complete certain Vendor Services (such as on-pack services). Red/E is not responsible for notifying Client of any retailer-related requirements, or for any liability arising from Client’s failure to obtain any retailer authorization. </span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Online Quote for Services.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">To place an order for Services, Client must log into the Platform under its Account and answer a series of questions, in response to which Red/E will provide Client (using Account information) with an online quote (“</span><b>Quote</b><span style="font-weight: 400;">”) which will provide (i) general nature and details of the Services; (ii) deliverables to be provided (“</span><b>Deliverables</b><span style="font-weight: 400;">”); (iii) timeline and deadline(s) for the Services; (iv) fees to be paid by Client for the Services and Deliverables (“</span><b>Fees</b><span style="font-weight: 400;">”); (v) and the date by which the Fees are due. When a Quote is accepted by Client, Red/E will generate and send Vendor an offer detailing the information in the Quote (the “</span><b>Offer</b><span style="font-weight: 400;">”). Red/E or Vendor may reject any Offer or portion thereof for any reason. Red/E will confirm, using Client’s Account contact information, whether Vendor accepts the Offer (an accepted offer is an “</span><b>Order</b><span style="font-weight: 400;">”), which Order may be conditioned certain Client deliverables (including Client Content, as defined below). </span></p>
                                    <p><span style="font-weight: 400;">Client acknowledges and agrees that once a Vendor has confirmed it will provide the Services and any Deliverables associated with an Order, Red/E will direct the relevant Vendor(s) to commence work and the Order shall be non-cancelable. Should Client request additional Services or Deliverables once a Vendor has commenced work, Red/E retains the right to change the Fees associated with the Quote, upon notice to Client. </span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Payment.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Upon Client’s acceptance of the Quote, Fees will be invoiced using Account information. All Fees are due to Red/E by the date specified in the Quote and are payable in U.S. dollars. Fees are calculated exclusive of all taxes. Ownership of assets and usage rights do not transfer to Client until invoices are paid in full. If Client has a good faith belief that it has been incorrectly billed by Red/E or Vendor, Client must contact Red/E in writing within seven (7) days following receipt of the applicable invoice specifying the calculation error and the amount of the adjustment or credit requested. Unless Client has notified Red/E of such dispute with invoiced Fees, payments not received by Red/E by the due date shall bear interest of one and one-half percent (1.5%) or the maximum rate allowed by law. Client shall be responsible for all reasonable third-party collection costs and legal fees incurred by Red/E in collecting amounts due. Red/E reserves the right to revoke any discounts applied to invoices past due. Paid unused services must be used within 90 days from the date of invoice to avoid a contract cancellation fee equal to the full amount of the original invoice. All fees are nonrefundable and are not subject to set-off.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Red/E Intellectual Property Ownership and License.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">The license and other terms and conditions governing your use of the Platform are governed by the Terms of Use found at www.rede-marketing.com/terms-of-use.</span></p>
                                    <p><span style="font-weight: 400;">The design tools provided on the Platform employ a limited number of elements, including fonts, color schemes, and design effects. Red/E reserves the right to use all such elements and to make all such elements available for use by other parties in the future. You do not obtain any right or claim to any of the individual design elements through your creation of a design and/or your incorporation of a design into one or more Services or Deliverables. Other Red/E customers may use the design tools to create designs that have similar or identical combinations of these elements and Red/E does not guarantee that your designs will not have similarities to other Services or Deliverables that were or are designed and used by other parties. Red/E provides no warranty of any kind that designs created using the design tools will not infringe, or be subject to a claim of infringing, the trademark or other rights of another party.</span></p>
                                    <ul>
                                    <li><b>Client Content.</b></li>
                                    </ul>
                                    <p><span style="font-weight: 400;">Client grants Red/E, each relevant Vendor and its and their affiliates and subsidiaries a license to display, perform, publish, modify and transmit all advertising and other content and materials, including text, illustrations, layout or copy (collectively, “</span><b>Client Content</b><span style="font-weight: 400;">”), furnished for the purposes contemplated hereby and pursuant to the relevant Order. If the format in which any Client Content submitted under this Agreement is published is converted into and distributed in any other formats or media, this Agreement grants Red/E and each relevant Vendor all rights necessary to convert publish and distribute such Client Content in such other formats and media consistent with any Order. Red/E may, in its sole discretion, refuse to publish any Client Content submitted to it or defer publication of any advertisement. </span></p>
                                    <p><span style="font-weight: 400;">Client assumes full responsibility and liability for all Client Content submitted and/or approved by Red/E or a Vendor. Client warrants that it has sufficient rights to permit Red/E to copy, distribute, use, modify, create derivative works of and vectorize any Client Content for the purpose of fulfilling Client’s Order and/or marketing products or services to Client. </span></p>
                                    <p><span style="font-weight: 400;">Client shall not either (i) take any action or (ii) upload, download, post, submit or otherwise distribute or facilitate distribution of any content on or through the Platform, that: infringes any patent, trademark, trade secret, copyright, right of publicity or other right of any other person or entity; is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another’s privacy, tortious, obscene, offensive, or profane; constitutes unauthorized or unsolicited advertising, junk, spam or bulk e-mail (including without limitation any postings to third party social media sites which are linked to the Platform); involves commercial activities and/or sales without Red/E’s prior written consent such as contests, sweepstakes, barter, advertising, or pyramid schemes; contains software viruses or any other computer codes, files, or programs that are designed or intended to disrupt, damage, limit or interfere with the proper function of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any system, data, password or other information of Red/E or any third party; or impersonates any person or entity, including any employee or representative of Red/E.</span></p>
                                    <p><span style="font-weight: 400;">Client shall deliver Client Content that is acceptable to and consistent with layout, copy, timing and mechanical requirements of Red/E or Vendor. Client shall clearly mark all advertising copy that might be mistaken as an article, commentary, or other non-advertising material as “advertisement”. Red/E assumes no liability for the return of Client Content in connection with Services. </span></p>
                                    <p><span style="font-weight: 400;">Client must present any changes or corrections to original layout and copy to Red/E Vendor in writing and in conformance with placement deadlines. Additional charges for corrections or late delivery may apply.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Third-Party Content.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Under no circumstances will Red/E be liable in any way for any content submitted to the Platform or to Client by any third party, including Vendor (“</span><b>Third-Party Content</b><span style="font-weight: 400;">”), including, but not limited to, any errors or omissions in any Third-Party Content, or any loss or damage of any kind incurred in connection with use of or exposure to any Third-Party Content, emailed, accessed, transmitted or otherwise made available to Client under this Agreement.</span></p>
                                    <p><span style="font-weight: 400;">The Platform may permit you to link to other websites or resources on the Internet, and other websites or resources may contain links to the Platform. When you access third-party websites, you do so at your own risk. These other websites are not under Red/E’s control, and you acknowledge that Red/E is not responsible or liable for the content, functions, accuracy, legality, appropriateness or any other aspect of such websites or resources. The inclusion of any such link does not imply endorsement by Red/E or any association with its operators. You further acknowledge and agree that Red/E shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such Third-Party Content, goods or services available on or through any such website or resource.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Term; Termination.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">This Agreement will commence on the Effective Date and will continue in full force and effect for a period of one (1) year (the “</span><b>Initial Term</b><span style="font-weight: 400;">”). Following the Initial Term, this Agreement will automatically renew for additional one (1) year periods (each, a “</span><b>Renewal Term</b><span style="font-weight: 400;">”, and together with the Initial Term, the “</span><b>Term</b><span style="font-weight: 400;">”). Either party may terminate this Agreement if the other party materially breaches this Agreement and does not materially cure such breach within thirty (30) days of such notice. Payment requirements are not subject to this cure period. Orders placed before termination are non-cancelable. </span></p>
                                    <p><span style="font-weight: 400;">After this Agreement terminates, the terms of this Agreement and the other Terms of Service that expressly or by their nature contemplate performance after the Agreement terminates or expires will survive and continue in full force and effect. For example, the provisions protecting Confidential and Proprietary Information, requiring arbitration, protecting intellectual property, requiring non-circumvention, indemnification, payment of fees, reimbursement and setting forth limitations of liability each, by their nature, contemplate performance or observance after this Agreement terminates. Additionally, if at the time this Agreement is terminated there are outstanding Services or Deliverables, then this Agreement shall survive until the completion and payment of such Services and Deliverables.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Confidential and Proprietary Information.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Each party shall keep confidential and not disclose to any other party or use, except as required by this Agreement, non-public information obtained from the other party; provided, however, that neither party shall be prohibited from disclosing or using information, (i) that at the time of disclosure is publicly available or becomes publicly available through no act or omission of the party having a confidentiality obligation under this section, (ii) that is or has been disclosed to such party by a third party who is not under (and to whom such party does not owe) an obligation of confidentiality with respect thereto, (iii) that is or has been independently acquired or developed by such party, (iv) to the minimum extent use or disclosure is required by court order or as otherwise required by law, on condition that notice of such requirement by law for such disclosure is given to the other parties prior to making any such use or disclosure.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>General Skills and Knowledge.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Notwithstanding anything to the contrary in this Agreement, Red/E shall not be prohibited or enjoined at any time by Client from utilizing any “skills or knowledge of a general nature” acquired during the course of performing the services specified under this Agreement. For purposes of this Agreement, “skills or knowledge of a general nature” shall include, without limitation, anything that might reasonably be learned or acquired in connection with similar work performed for another Client.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Warranty; Disclaimer.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Red/E warrants that the Red/E Services will be performed in a professional and workmanlike manner, in accordance with generally accepted applicable professional and industry standards. Red/E expressly disclaims all liability relating to the Vendor Services, including any Third-Party Content incorporated therein, made a part of or otherwise provided to Client as part of the Vendor Services. EXCEPT FOR THE EXPRESS WARRANTIES STATED HEREIN, ALL SERVICES ARE PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, AND Red/E HEREBY DISCLAIMS ALL WARRANTIES, INCLUDING ALL WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT, and the stated express warranties are in lieu of all other obligations or performance liabilities arising out of or in connection with the Services.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Indemnity.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Client and Red/E, its affiliates, and their respective officers, directors, employees, agents, licensors, and suppliers, agree to indemnify, defend, and hold the other harmless from and against any third-party claims, costs, liabilities, and expenses (including reasonable attorneys’ fees) paid or payable to an unaffiliated third party arising from (i) any claim that party has infringed another’s intellectual property right; (ii) violation of this Agreement; or (iii) any violation of applicable laws. Client shall also indemnify, defend and hold Red/E, its affiliates, and their respective officers, directors, employees, agents, licensors, and suppliers from and against any third-party claims, costs, liabilities and expenses (including reasonable attorneys’ fees) paid or payable to an unaffiliated third party arising from a breach of any agreement between it and a Vendor or any other third party. </span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Limitation of Liability.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">EXCEPT FOR A PARTY’S BREACH OF SECTION 10 (CONFIDENTIAL AND PROPRIETARY INFORMATION), NEITHER PARTY SHALL BE LIABLE TO THE OTHER PARTY WITH RESPECT TO THE SUBJECT MATTER OF THIS AGREEMENT, WHETHER IN CONTRACT TORT, NEGLIGENCE, OR ANY OTHER LEGAL OR EQUITABLE THEORY, FOR (I) ANY DAMAGES RESULTING FROM LOSS OF DATA, PROFITS OR USE; OR (II) FOR ANY SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES; OR (III) FOR ANY AMOUNTS IN EXCESS OF THE AMOUNTS PAID OR PAYABLE TO Red/E UNDER THIS AGREEMENT DURING THE TWELVE (12) MONTH PERIOD PRECEDING THE EVENT GIVING RISE TO LIABILITY.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Non-Circumvention and Non-Solicitation of Vendors.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Connecting Clients with Vendors is an integral part of Red/E’s business model, and maintaining a supply of Vendors is essential to Red/E’s core business. Client represents and warrants that it will not attempt to circumvent, or circumvent, any of the communication or payment methods provided by the Platform: this includes, but is not limited to (i) submitting any proposals or soliciting any Vendor it has previously engaged through the Platform other than through the Platform; and (ii) paying any fees associated with the Services other than to Red/E as provided in this Agreement. During the term of this Agreement and for a period of one (1) year after, Client represents and warrants it will not pay Vendors introduced to Client by Red/E outside the Platform nor directly or indirectly solicit such Vendors to provide services outside the Platform. Client further represents and warrants the Platform will serve as the primary means of communication between Client and Vendor regarding the Vendor Services and Deliverables, which is essential to Red/E’s ability to provide Services and assist Client in its usage of the Platform and Vendor delivery of Vendor Services.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Suspension of Access.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Red/E retains the right, to immediately prevent or restrict access to the Platform or take any other action as necessary in case of technical problems, infringing or objectionable material, inaccurate listings, inappropriately categorized products or services, or actions otherwise prohibited by applicable law, the guidelines contained on the Platform, or for any other reason in the sole and absolute discretion of Red/E, and to correct any inaccurate listing or technical problems on the Platform.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Vendor Dispute; Release.</b></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">In the event of a dispute between Client and Vendor with respect to the Vendor Services or Deliverables, such dispute will be submitted to Red/E in writing on, before, but no later than ten (10) business days from Client’s receipt of the invoice(s) for same services, and if following review, the dispute(s) are found to be valid, Red/E will resolve such dispute(s) in its reasonable discretion. Client agrees that any such resolution will be final and binding.</span></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Miscellaneous.</b><span style="font-weight: 400;">
                                    <p></p>
                                    <ol>
                                    <li style="font-weight: 400;"><b>Assignment.</b></li>
                                    </ol>
                                    </span></li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Client may not assign, delegate or transfer this Agreement or any rights or obligations hereunder in any way (by operation of law or otherwise) without Red/E’s prior written consent. Red/E may transfer, assign, subcontract or delegate this Agreement and any rights and obligations without consent.</span></p>
                                    <ol>
                                    <li style="list-style-type: none;">
                                    <ol>
                                    <li style="font-weight: 400;"><b>Independent Contractors.</b></li>
                                    </ol>
                                    </li>
                                    </ol>
                                    <p><span style="font-weight: 400;">For all purposes under this Agreement each party shall be and act as an independent contractor of the other and shall not bind nor attempt to bind the other to any contract.</span></p>
                                    <ol>
                                    <li style="list-style-type: none;">
                                    <ol>
                                    <li style="font-weight: 400;"><b>Taxes.</b></li>
                                    </ol>
                                    </li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Red/E will be solely responsible for its income taxes in connection with this Agreement and Client will be responsible for sales, use and similar taxes, if any.</span></p>
                                    <ol>
                                    <li style="list-style-type: none;">
                                    <ol>
                                    <li style="font-weight: 400;"><b>Force Majeure. </b></li>
                                    </ol>
                                    </li>
                                    </ol>
                                    <p><span style="font-weight: 400;">The parties to this Agreement will not be responsible for the failure to perform or any delay in performance of any obligation hereunder (except for a payment obligation) due to labor disturbances, accidents, fires, floods, telecommunications or Internet failures, strikes, wars, riots, rebellions, blockades, acts of government, governmental requirements and regulations or restrictions imposed by law or any other similar conditions beyond the reasonable control of such party. The time for performance of such party will be extended by the period of such delay. Irrespective of any extension of time, if an event of Force Majeure occurs and its effect continues for a period of 60 days, either the party may give to the other a 30-day notice of termination. &nbsp;If, at the end of the 30-day period, the effect of the Force Majeure continues, the Agreement and the other Terms of Service will terminate, except as provided in Section 10.</span></p>
                                    <ol>
                                    <li style="list-style-type: none;">
                                    <ol>
                                    <li style="font-weight: 400;"><b>Entire Agreement.</b></li>
                                    </ol>
                                    </li>
                                    </ol>
                                    <p><span style="font-weight: 400;">This Agreement, along with the other Terms of Service, which are incorporated by reference, sets forth the entire understanding of the parties as to the subject matter herein and may not be modified except in a writing executed by both parties.</span></p>
                                    <ol>
                                    <li style="list-style-type: none;">
                                    <ol>
                                    <li style="font-weight: 400;"><b>Notices.</b></li>
                                    </ol>
                                    </li>
                                    </ol>
                                    <p><span style="font-weight: 400;">Except as otherwise set forth herein, any notices in connection with this Agreement will be in writing and sent by first class U.S. mail, major commercial rapid delivery courier service, or confirmed email, to Red/E c/o Advantage Sales &amp; Marketing LLC, 18100 Von Karman Ave., Suite 1000, Irvine, CA 92612 (or such other address as may be properly specified by written notice hereunder).</span></p>
                                    <ol>
                                    <li style="list-style-type: none;">
                                    <ol>
                                    <li style="font-weight: 400;"><b>Choice of Law.</b></li>
                                    </ol>
                                    </li>
                                    </ol>
                                    <p><span style="font-weight: 400;">This Agreement is governed by and will be construed under the laws of the State of Delaware, without regard to the conflicts of laws provisions thereof and excluding the United Nations Convention on Contracts for the International Sale of Goods (CISG). </span></p>
                                    <ol>
                                    <li style="list-style-type: none;">
                                    <ol>
                                    <li style="font-weight: 400;"><b>Arbitration. </b></li>
                                    </ol>
                                    </li>
                                    </ol>
                                    <p><span style="font-weight: 400;">YOU AND Red/E AGREE (A) TO GIVE UP ANY RIGHTS TO PARTICIPATE IN A CLASS ACTION OR REPRESENTATIVE ACTION WITH RESPECT TO ANY CLAIM, DISPUTE OR CONTROVERSY (WHETHER IN CONTRACT, TORT OR OTHERWISE, WHETHER PRE-EXISTING, PRESENT OR FUTURE, AND INCLUDING STATUTORY, CONSUMER PROTECTION, COMMON LAW, INTENTIONAL TORT, INJUNCTIVE AND EQUITABLE CLAIMS) BETWEEN YOU AND US ARISING FROM OR RELATING IN ANY WAY TO THE PLATFORM OR YOUR PURCHASE OF SERVICES (COLLECTIVELY, A “</span><b>DISPUTE</b><span style="font-weight: 400;">“) AND (B) ANY DISPUTE SHALL BE SUBMITTED TO INDIVIDUAL, BINDING ARBITRATION, EXCEPT THAT, TO THE EXTENT YOU HAVE IN ANY MANNER VIOLATED OR THREATENED TO VIOLATE Red/E’S INTELLECTUAL PROPERTY RIGHTS, Red/E MAY SEEK INJUNCTIVE, EQUITABLE, OR OTHER APPROPRIATE RELIEF IN ANY STATE OR FEDERAL COURT IN THE STATE OF DELAWARE, AND YOU CONSENT TO EXCLUSIVE JURISDICTION AND VENUE IN SUCH COURTS. . </span></p>
                                    <p><span style="font-weight: 400;">NETIHER PARTY WILL HAVE THE RIGHT TO LITIGATE THAT DISPUTE IN COURT OR HAVE A JURY TRIAL ON THAT DISPUTE. EACH PARTY ACKNOWLEDGES THAT RIGHTS THAT IT WOULD HAVE IF IT WENT TO COURT MAY BE UNAVAILABLE OR MAY BE LIMITED IN ARBITRATION.</span></p>
                                    <p><span style="font-weight: 400;">Arbitration will be administered by JAMS arbitrators in accordance with the JAMS Rules then in effect, except as modified by this Section 18(h). (The JAMS Rules are available at </span><a target="_blank" href="http://www.adr.org/rules"><span style="font-weight: 400;">www.jamsadr.com</span></a><span style="font-weight: 400;">.) The Federal Arbitration Act will govern the interpretation and enforcement of this section.</span></p>
                                    <p><span style="font-weight: 400;">JAMS will have exclusive authority to resolve any dispute relating to arbitrability and/or enforceability of this arbitration provision, including any unconscionability challenge or any other challenge that the arbitration provision or the Agreement is void, voidable or otherwise invalid. JAMS will be empowered to grant whatever relief would be available in court under law or in equity. Any award of the arbitrator(s) will be final and binding on each of the parties, and may be entered as a judgment in any court of competent jurisdiction.</span></p>
                                    <p><span style="font-weight: 400;">If you prevail on any Dispute that affords the prevailing party attorneys’ fees, the arbitrator may award reasonable fees to you under the standards for fee shifting provided by law. </span></p>
                                    <p><span style="font-weight: 400;">You agree to an arbitration on an individual basis. In any dispute, NEITHER YOU NOR Red/E WILL BE ENTITLED TO JOIN OR CONSOLIDATE CLAIMS BY OR AGAINST OTHER CUSTOMERS IN ARBITRATION OR OTHERWISE PARTICIPATE IN ANY CLAIM AS A CLASS REPRESENTATIVE, CLASS MEMBER OR IN A PRIVATE ATTORNEY GENERAL CAPACITY. The arbitral tribunal may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding. </span></p>
                                    <p><span style="font-weight: 400;">If any provision of this Section 18(h) is found unenforceable, the unenforceable provision will be severed and the remaining terms will be enforced.</span></p>
                                    <ol>
                                    <li style="list-style-type: none;">
                                    <ol>
                                    <li style="font-weight: 400;"><b>Limitation on Time to File Claims</b></li>
                                    </ol>
                                    </li>
                                    </ol>
                                    <p><span style="font-weight: 400;">ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF USE OR THE PLATFORM OR THE SERVICES MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED. </span></p>
                                    <p><b>Red/E Design and Creative Terms of Service </b></p>
                                    <table>
                                    <tbody>
                                    <tr>
                                    <td><b>PLEASE READ THESE DESIGN AND CREATIVE TERMS OF SERVICE (THESE “CREATIVE TERMS”) CAREFULLY BEFORE USING Red/E’S DESIGN AND OTHER CREATIVE SERVICES (THE “CREATIVE SERVICES”) OFFERED BY Red/E MARKETING, LLC (“Red/E”). THE Red/E MARKETING, LLC TERMS AND CONDITIONS OF SERVICES (“GENERAL Red/E TERMS”) ARE INCORPORATED BY REFERENCE INTO AND MADE A PART OF THESE DESIGN AND CREATIVE TERMS OF SERVICE, EXCEPT TO THE LIMITED EXTENT MODIFIED BELOW. BY CLICKING THE “SUBMIT” BUTTON OR BY REQUESTING THE SERVICES IN ANY MANNER (THE FIRST DATE ON WHICH EITHER OF THESE EVENTS OCCURS, THE “EFFECTIVE DATE”), YOU OR THE ENTITY YOU REPRESENT (“CLIENT”) AGREE THAT YOU HAVE READ AND AGREE TO BE BOUND BY AND A PARTY TO THESE CREATIVE TERMS. YOU REPRESENT AND WARRANT THAT YOU ARE AUTHORIZED TO BIND CLIENT. USE OF Red/E’S CREATIVE SERVICES IS EXPRESSLY CONDITIONED UPON CLIENT’S ASSENT TO ALL THE TERMS AND CONDITIONS OF THESE CREATIVE TERMS (INCLUDING THE GENERAL Red/E TERMS AND THE RELATED TERMS OF SERVICE), TO THE EXCLUSION OF ALL OTHER TERMS. IF THESE CREATIVE TERMS ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO SUCH TERMS. IF CLIENT DOES NOT UNCONDITIONALLY AGREE TO ALL THE TERMS AND CONDITIONS OF THESE CREATIVE TERMS, NAVIGATE AWAY FROM THIS PAGE AND CLIENT WILL HAVE NO RIGHT TO USE THE CREATIVE SERVICES.</b><p></p>
                                    <p><span style="font-weight: 400;">Red/E reserves the right to make changes to these Creative Terms and to the Creative Services at any time without prior notice. Capitalized terms used but not defined herein shall have the meanings ascribed thereto in the General Red/E Terms. </span></p></td>
                                    </tr>
                                    </tbody>
                                    </table>
                                    <table>
                                    <tbody>
                                    <tr>
                                    <td>
                                    <ul>
                                    <li><b>Designs.</b></li>
                                    </ul>
                                    <p><span style="font-weight: 400;">The designs and/or written copy (collectively, “</span><b>Designs</b><span style="font-weight: 400;">”) prepared by Red/E for you as part of your Creative Services project may have similarities to Designs prepared by Red/E for other parties. You are obtaining no right or claim of any kind to any individual Design (or any element thereof) provided by Red/E, and Red/E reserves the right to use the same or similar Design or elements thereof in other Creative Services projects or otherwise for other parties in the future. Except for the specific Creative Services project content provided to Red/E by you, all rights in all Creative Services work product, including without limitation both final Designs and all interim and draft Designs, are retained by Red/E. </span></p></td>
                                    </tr>
                                    </tbody>
                                    </table>
                                    <ul>
                                    <li><b>Requirements.</b></li>
                                    </ul>
                                    <table>
                                    <tbody>
                                    <tr>
                                    <td><span style="font-weight: 400;"><br>
                                    </span><span style="font-weight: 400;">Red/E reserves the right, in Red/E’s sole discretion, to refuse to accept any Creative Services project or to terminate any Creative Services project prior to completion at any time and for any reason. You agree that Red/E shall have no liability of any kind to you or to any third party arising from such refusal or termination. </span><p></p>
                                    <p><span style="font-weight: 400;">Red/E reserves the right to use any Designs and/or your finished Creative Services project products as sample work for advertising and promotional purposes and for internal purposes. </span></p>
                                    <p><span style="font-weight: 400;">First and second Design iterations may be rejected within 48 hours of being completed by the Red/E Creative Services team and placed in your Red/E Account. If you do not reject your Design within such 48-hour period or for the third Design iteration, you will be deemed to have accepted such Design, and all amounts paid or payable by you for the Creative Services project will be nonrefundable. </span></p>
                                    <p><span style="font-weight: 400;">It is your responsibility to provide Customer Content if needed to complete the project. You must contact Red/E with any changes, updates, or enhancements to the project you are requesting starting from date of sale. </span></p>
                                    <p><span style="font-weight: 400;">You must contact </span><a target="_blank" href="mailto:info@rede-marketing.com"><span style="font-weight: 400;">info@rede-marketing.com</span></a><span style="font-weight: 400;"> for any requests to cancel services. </span></p></td>
                                    </tr>
                                    </tbody>
                                    </table>
                                    <ul>
                                    <li><b>Damages and Liabilities.</b></li>
                                    </ul>
                                    <table>
                                    <tbody>
                                    <tr>
                                    <td><span style="font-weight: 400;"><br>
                                    </span><span style="font-weight: 400;">Red/E disclaims and shall not be liable for any loss, injury, cost or damage suffered by Client or any third party, and shall in no event be liable for consequential, special, or indirect or incidental damages (including without limitation, damages for loss of business profits, business interruption, or loss of data), arising out of or in any way connected with the use of the Designs and any information available on or related to such Designs, and the delay or inability to use the Red/E site or any information, in each case even if Red/E has been advised of the possibility of such damages. </span><p></p>
                                    <p><span style="font-weight: 400;">Red/E provides no warranty of any kind that any Design will not infringe, or be subject to a claim of infringing, the trademark or other rights of another party. It is solely your responsibility to obtain the advice of an attorney regarding whether any such Design is legally available for your use and does not infringe the rights of another party. </span></p>
                                    <p><span style="font-weight: 400;">All delivery times are estimates only, and Red/E is not responsible for any late Creative Services projects and/or impact to Client’s business due to a late project and/or printing. </span></p></td>
                                    </tr>
                                    </tbody>
                                    </table>
                                    <p><b></b></p>
                                    <p><b>Red/E Social Media Marketing Terms of Service </b></p>
                                    <p><b>PLEASE READ THESE SOCIAL MEDIA MARKETING TERMS OF SERVICE (THESE “SOCIAL MEDIA TERMS”) CAREFULLY BEFORE USING Red/E’S SOCIAL MEDIA SERVICES (THE “SOCIAL MEDIA SERVICES”) OFFERED BY Red/E MARKETING, LLC (“Red/E”). THE Red/E MARKETING, LLC TERMS AND CONDITIONS OF SERVICES (“GENERAL Red/E TERMS”) ARE INCORPORATED BY REFERENCE INTO AND MADE A PART OF THESE SOCIAL MEDIA MARKETING TERMS OF SERVICE. BY CLICKING THE “SUBMIT” BUTTON OR BY REQUESTING THE SERVICES IN ANY MANNER (THE FIRST DATE ON WHICH EITHER OF THESE EVENTS OCCURS, THE “EFFECTIVE DATE”), YOU OR THE ENTITY YOU REPRESENT (“CLIENT”) AGREE THAT YOU HAVE READ AND AGREE TO BE BOUND BY AND A PARTY TO THESE SOCIAL MEDIA TERMS. YOU REPRESENT AND WARRANT THAT YOU ARE AUTHORIZED TO BIND CLIENT. USE OF Red/E’S SOCIAL MEDIA SERVICES IS EXPRESSLY CONDITIONED UPON CLIENT’S ASSENT TO ALL THE TERMS AND CONDITIONS OF THESE SOCIAL MEDIA TERMS (INCLUDING THE GENERAL Red/E TERMS AND THE RELATED TERMS OF SERVICE), TO THE EXCLUSION OF ALL OTHER TERMS. IF THESE SOCIAL MEDIA TERMS ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO SUCH TERMS. IF CLIENT DOES NOT UNCONDITIONALLY AGREE TO ALL THESE SOCIAL MEDIA TERMS, NAVIGATE AWAY FROM THIS PAGE AND CLIENT WILL HAVE NO RIGHT TO USE THE SOCIAL MEDIA SERVICES. </b></p>
                                    <p><span style="font-weight: 400;">Red/E’s Social Media Services have been developed to facilitate the promotion of your business and/or interests on social media platforms such as Facebook (each, a “</span><b>Social Media Platform</b><span style="font-weight: 400;">”), using Social Media Platforms’ ad inventory and consistent with such Social Media Platforms’ guidelines in place at the time. </span></p>
                                    <p><span style="font-weight: 400;">To complete the process of creating and customizing your Social Media Platform page and then advertising on one or more Social Media Platforms, you may be required to accept additional terms and conditions from the relevant Social Media Platform, including the following Facebook terms and conditions: </span></p>
                                    <ul>
                                    <li><span style="font-weight: 400;">Facebook Statement of Rights and Responsibilities (</span><a target="_blank" href="https://www.facebook.com/legal/terms"><span style="font-weight: 400;">https://www.facebook.com/legal/terms</span></a><span style="font-weight: 400;">)</span></li>
                                    <li><span style="font-weight: 400;">Facebook Advertising Guidelines (</span><a target="_blank" href="https://www.facebook.com/ad_guidelines.php"><span style="font-weight: 400;">https://www.facebook.com/ad_guidelines.php</span></a><span style="font-weight: 400;">)</span></li>
                                    <li><span style="font-weight: 400;">Facebook Community Payments Terms (</span><a target="_blank" href="https://www.facebook.com/payments_terms"><span style="font-weight: 400;">https://www.facebook.com/payments_terms</span></a><span style="font-weight: 400;">)</span></li>
                                    </ul>
                                    <p><span style="font-weight: 400;">Each Social Media Platform’s guidelines are subject to change and there may be a period where the Social Media Services may need to be updated or redeveloped to accommodate this change, if at all. In no case will Red/E be liable to you for loss of business or profits; incidental or consequential damages; or costs in excess of billing for services related to your purchase of the Social Media Services, whether as a result of errors, mistakes or failure by Red/E to perform services, or otherwise. Red/E reserves the right, in Red/E’s sole discretion, to refuse to accept any particular use of a Social Media Service or to terminate any particular use of the Social Media Services prior to completion at any time and for any reason. You agree that Red/E shall have no liability of any kind to you or to any third party arising from such refusal or termination. </span></p>
                                    <p><span style="font-weight: 400;">Red/E reserves the right to make changes to these Social Media Terms and to the Social Media Services without prior notice.</span></p>
                                </div>