<?php

// add the publix settings item to the Settings menu
if( function_exists('acf_add_options_page') ) {
	acf_add_options_sub_page(array(
		'page_title' 	=> 'Publix Form Settings',
		'menu_title'	=> 'Publix Form Settings',
		'parent_slug'	=> 'options-general.php',
	));
}

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5eb197bc77d30',
	'title' => 'Publix Co-op Calendar',
	'fields' => array(
		array(
			'key' => 'field_5eb1982bdd22d',
			'label' => 'Entry',
			'name' => 'coop_cal_entry',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Entry',
			'sub_fields' => array(
				array(
					'key' => 'field_coopcaluniqid',
					'label' => 'Title (must be unique)',
					'name' => 'unique_id',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5eb19849dd22e',
					'label' => 'Start Date',
					'name' => 'start_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'm/d/Y',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5eb19877dd22f',
					'label' => 'End Date',
					'name' => 'end_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'm/d/Y',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5eb19888dd230',
					'label' => 'Popular Holidays',
					'name' => 'popular_holidays',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5eb19926dd232',
					'label' => 'Submission Start',
					'name' => 'submission_start',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'm/d/Y',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5eb19938dd233',
					'label' => 'Submission End',
					'name' => 'submission_end',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'm/d/Y',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5eb19944dd234',
					'label' => 'Approval Notification Date',
					'name' => 'approval_notification_date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'm/d/Y',
					'first_day' => 1,
				),
				array(
					'key' => 'field_5eb198a6dd231',
					'label' => 'Theme Pages',
					'name' => 'theme_pages',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'stockup' => 'Stock Up',
						'newitem' => 'New Item',
						'gameday' => 'Game Day',
						'plantbased' => 'Plant Based',
						'organic' => 'Organic',
						'coolfoods' => 'Cool Foods',
						'breakfast' => 'Breakfast',
						'icecream' => 'Ice Cream',
						'hydration' => 'Hydration',
						'backtoschool' => 'Back to School',
						'storm' => 'Hurricane/Storm Basics',
						'everyday' => 'Everyday Delicious',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'horizontal',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-publix-form-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;